"""
Aurelia Cognitive OS V4 - Schema-Bound Model Outputs
=====================================================
Absolute Invariant: Internal local models must never return unconstrained prose
for cognitive reasoning steps. All model inferences must validate against these schemas.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Tuple, Optional, Any


@dataclass(frozen=True)
class HypothesisProposal:
    """A proposed strategic trajectory generated by reasoning cortex."""
    id: str
    strategy_type: str                   # e.g., "aggressive_leverage", "risk_mitigated", "structural_pivot"
    headline: str
    assumptions: Tuple[str, ...]
    proposed_actions: Tuple[str, ...]
    expected_upside: str
    expected_downside: str
    time_to_value_months: float
    confidence: float


@dataclass(frozen=True)
class ReasoningResult:
    """Structured reasoning output returned by the reasoning cortex."""
    interpretation: str
    hypotheses: Tuple[HypothesisProposal, ...]
    identified_assumptions: Tuple[str, ...]
    uncertainties: Tuple[str, ...]
    recommended_hypothesis_id: str
    confidence: float


@dataclass(frozen=True)
class CritiqueResult:
    """Structured critique returned by an independent critic."""
    critic_role: str                     # "strategic_fit", "risk_assessor", "evidence_auditor"
    score: float                         # 0.0 to 1.0
    passed: bool
    unsupported_assumptions: Tuple[str, ...]
    flagged_risks: Tuple[str, ...]
    critique_notes: str
